#!/bin/sh
rm -f GBT7714-2005N.bst Makefile sjtubannerred.pdf thesis.tex
ln -s ../thesis-template/GBT7714-2005N.bst .
ln -s ../thesis-template/Makefile .
ln -s ../thesis-template/sjtubannerred.pdf .
ln -s ../thesis-template/thesis.tex .
